// A seeded, already-published Asia Source Issue 01 (15 to 30 June 2026), taken
// from the first printed issue. It lets the public reader and the Studio render
// fully with no API key and no Supabase, and it doubles as the format reference.
// Source URLs point at the publishing organisation where an exact article link
// was not recorded on the printed issue.

import type { Issue, IssueItem } from "./types";

const ISSUE_ID = "sample-asia-source-01";

export const SAMPLE_ISSUE: Issue = {
  id: ISSUE_ID,
  publication: "asia-source",
  kind: "issue",
  issueNumber: 1,
  periodStart: "2026-06-15",
  periodEnd: "2026-06-30",
  status: "published",
  title: "Ceasefire eases oil, but freight and FX keep buyers cautious",
  intro:
    "Oil and naphtha costs retreated as the US to Iran ceasefire improved Hormuz flows, yet renewed vessel incidents, elevated freight risk and sharp Asian FX moves kept buyers cautious. The sourcing priority remains dual supply, shorter price validity windows and stronger compliance evidence.",
  body: "",
  closing:
    "Reconfirm Gulf route freight validity, hedge major FX exposures, audit origin and forced labour documentation, and identify one qualified alternate source for every critical intermediate.",
  publishedAt: "2026-06-30T09:00:00.000Z",
  createdAt: "2026-06-30T09:00:00.000Z",
};

type SeedItem = Omit<IssueItem, "id" | "issueId">;

const SEED_ITEMS: SeedItem[] = [
  {
    position: 1,
    bucket: "AI and technology in chemicals",
    headline: "AI accelerates chemical discovery",
    body: "AI-assisted molecular discovery is moving from experimentation toward practical screening, formulation and process optimisation. Chemical teams should pair faster digital discovery with human review, IP controls and responsible-use protocols.",
    sourceName: "OPCW",
    sourceUrl: "https://www.opcw.org/",
    sourceDate: "10 Jun 2026",
    included: true,
  },
  {
    position: 2,
    bucket: "China capacity and Asia supply glut",
    headline: "China's capacity surge deepens Asia's supply glut",
    body: "Asia's petrochemical imbalance remains structural: China continues adding scale while older and less-efficient assets across the region face upgrades, consolidation or closure. Expect aggressive export offers and margin pressure in commodity chains.",
    sourceName: "ICIS",
    sourceUrl: "https://www.icis.com/",
    sourceDate: "APIC 2026",
    included: true,
  },
  {
    position: 3,
    bucket: "Freight and logistics risk",
    headline: "Hormuz incident rekindles freight risk",
    body: "Hormuz remained the key freight risk. A vessel incident near Oman on 25 June interrupted evacuation efforts and lifted oil prices, showing that route availability, insurance and tanker positioning, not crude alone, must guide landed-cost planning.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/",
    sourceDate: "25 Jun 2026",
    included: true,
  },
  {
    position: 4,
    bucket: "Feedstock and naphtha margins",
    headline: "Asian naphtha margins hit a multi-year low",
    body: "Asian naphtha moved into contango and its refining margin fell to roughly US$45/tonne over Brent by mid-June, the weakest since late 2023. Lower feedstock costs may support downstream buyers, but weak margins signal soft demand.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/",
    sourceDate: "16 Jun 2026",
    included: true,
  },
  {
    position: 5,
    bucket: "Geopolitics and energy security",
    headline: "Gulf tensions ease, but the risk premium remains",
    body: "The US to Iran interim arrangement reduced immediate energy-market stress, but the security premium has not disappeared. Procurement teams should maintain alternate ports, shipment visibility and emergency inventory for Gulf-linked raw materials.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/",
    sourceDate: "19 Jun 2026",
    included: true,
  },
  {
    position: 6,
    bucket: "Contracts and negotiation strategy",
    headline: "Contracts shift toward trigger-based protection",
    body: "Use trigger-based contracts: revise freight, energy and FX clauses when agreed thresholds are crossed. Scenario plans should cover a renewed Hormuz closure, 5 to 10 percent currency swings and delayed vessel allocation.",
    sourceName: "UK Government Office for Science",
    sourceUrl: "https://www.gov.uk/government/organisations/government-office-for-science",
    sourceDate: "15 Jun 2026",
    included: true,
  },
  {
    position: 7,
    bucket: "Compliance and forced labour scrutiny",
    headline: "Forced-labour proof becomes a market-access essential",
    body: "Forced-labour scrutiny is becoming a tariff and market-access issue. Exporters need traceable supplier declarations, origin records and auditable chain-of-custody evidence, not only product certificates, to defend customer access.",
    sourceName: "European Commission",
    sourceUrl: "https://commission.europa.eu/",
    sourceDate: "Jun 2026",
    included: true,
  },
  {
    position: 8,
    bucket: "Tier-2 and supply chain mapping",
    headline: "Hidden tier-2 dependencies come into focus",
    body: "The UK's new supply-chain resilience analysis reinforces a practical lesson: concentration risk often sits below Tier 1. Map critical intermediates, utilities, logistics nodes and single-country dependencies before disruption occurs.",
    sourceName: "UK Government Office for Science",
    sourceUrl: "https://www.gov.uk/government/organisations/government-office-for-science",
    sourceDate: "15 Jun 2026",
    included: true,
  },
  {
    position: 9,
    bucket: "Digital tools and control towers",
    headline: "Control towers move from visibility to action",
    body: "Control towers are most valuable when they combine supplier data, shipment milestones, FX exposure, quality records and exception alerts. The next advantage is not more dashboards, but faster decisions from verified data.",
    sourceName: "UK Government Office for Science",
    sourceUrl: "https://www.gov.uk/government/organisations/government-office-for-science",
    sourceDate: "15 Jun 2026",
    included: true,
  },
  {
    position: 10,
    bucket: "Environment and regulation in Asia",
    headline: "Environmental scrutiny tightens across Asia",
    body: "Asian regulators are tightening water, pollution and chemical-management enforcement. Buyers should validate permits, effluent controls, waste handling and energy intensity during supplier qualification, especially for water-intensive chemistry.",
    sourceName: "ICIS",
    sourceUrl: "https://www.icis.com/",
    sourceDate: "APIC 2026",
    included: true,
  },
  {
    position: 11,
    bucket: "Procurement strategy and risk scoring",
    headline: "The lowest quote may carry the highest risk",
    body: "Commodity overcapacity creates negotiation leverage, but the lowest quote may hide utilisation, credit or shutdown risk. Award business using a balanced scorecard covering cost, continuity, compliance, quality and responsiveness.",
    sourceName: "ICIS",
    sourceUrl: "https://www.icis.com/",
    sourceDate: "APIC 2026",
    included: true,
  },
  {
    position: 12,
    bucket: "Specialty versus commodity chemicals",
    headline: "Specialty chemicals outpace commodity plays",
    body: "Regional winners are shifting toward specialty materials, advanced polymers and energy-transition applications. Commodity producers remain exposed to utilisation pressure, weak spreads and policy-led restructuring.",
    sourceName: "ICIS",
    sourceUrl: "https://www.icis.com/",
    sourceDate: "APIC 2026",
    included: true,
  },
  {
    position: 13,
    bucket: "Plant operations and digital twins",
    headline: "Digital twins move closer to plant operations",
    body: "AI, digital twins and predictive maintenance can shorten scale-up cycles and reduce unplanned downtime. Early deployment should focus on high-value use cases with clean plant data and measurable operational outcomes.",
    sourceName: "Scientific Reports",
    sourceUrl: "https://www.nature.com/srep/",
    sourceDate: "9 Mar 2026",
    included: true,
  },
  {
    position: 14,
    bucket: "Oil prices and Asian currencies",
    headline: "Cheaper oil, weaker Asian currencies",
    body: "Brent ended the quarter sharply lower, while the Indian rupee closed 30 June near 94.66 per US dollar and the yen weakened beyond 162 per US dollar. Importers gained energy relief but faced significant currency-driven replacement-cost risk.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/",
    sourceDate: "30 Jun 2026",
    included: true,
  },
  {
    position: 15,
    bucket: "Trade policy and tariffs",
    headline: "EU and US tariff easing reshapes competition",
    body: "The EU moved to implement tariff reductions agreed with the US, temporarily lowering transatlantic trade friction. Asian suppliers should track resulting preference shifts, rules of origin and indirect competitive effects.",
    sourceName: "Council of the EU",
    sourceUrl: "https://www.consilium.europa.eu/",
    sourceDate: "25 Jun 2026",
    included: true,
  },
  {
    position: 16,
    bucket: "Quality, substitution and counterfeit risk",
    headline: "Volatility raises substitution and counterfeit risk",
    body: "High-volatility markets increase substitution and counterfeit risk. Strengthen incoming identity testing, retain samples, change-control approvals and supplier CAPA closure. Remote documentation alone is insufficient for critical materials.",
    sourceName: "WHO",
    sourceUrl: "https://www.who.int/",
    sourceDate: "Jun 2026",
    included: true,
  },
];

export const SAMPLE_ITEMS: IssueItem[] = SEED_ITEMS.map((it) => ({
  ...it,
  id: `${ISSUE_ID}-item-${it.position}`,
  issueId: ISSUE_ID,
}));
